-- Letsgo2Travel Supabase Schema Definition
-- Supabase SQL Editor içinde çalıştırılabilir.

CREATE TABLE IF NOT EXISTS public.biletler (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  origin TEXT NOT NULL,
  destination TEXT NOT NULL,
  origin_code VARCHAR(10) NOT NULL,
  destination_code VARCHAR(10) NOT NULL,
  price INT NOT NULL,
  currency VARCHAR(10) DEFAULT 'TRY',
  airline TEXT,
  travel_period TEXT,
  trip_type TEXT DEFAULT 'Gidiş dönüş',
  visa_type TEXT NOT NULL DEFAULT 'vizesiz',
  region TEXT NOT NULL DEFAULT 'Genel',
  image_url TEXT,
  affiliate_url TEXT NOT NULL,
  active BOOLEAN DEFAULT true,
  clicks INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT NOT NULL,
  read_time VARCHAR(20) NOT NULL,
  image_url TEXT,
  author VARCHAR(100) DEFAULT 'Letsgo2Travel',
  published_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.country_guides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  country_code VARCHAR(10) NOT NULL,
  country_name TEXT NOT NULL,
  continent TEXT NOT NULL,
  region TEXT NOT NULL,
  emoji VARCHAR(10),
  visa_status VARCHAR(50) NOT NULL,
  visa_note TEXT,
  avg_flight_price INT NOT NULL DEFAULT 0,
  flight_duration VARCHAR(50),
  best_months VARCHAR(100),
  airport_code VARCHAR(10),
  is_popular BOOLEAN DEFAULT false,
  hero_image_url TEXT,
  content_markdown TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  youtube_id VARCHAR(50) UNIQUE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  is_active BOOLEAN DEFAULT true,
  subscribed_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.biletler ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.country_guides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "biletler public select" ON public.biletler;
DROP POLICY IF EXISTS "blogs public select" ON public.blogs;
DROP POLICY IF EXISTS "country guides public select" ON public.country_guides;
DROP POLICY IF EXISTS "videos public select" ON public.videos;
DROP POLICY IF EXISTS "subscribers insert" ON public.subscribers;

CREATE POLICY "biletler public select" ON public.biletler FOR SELECT USING (active = true);
CREATE POLICY "blogs public select" ON public.blogs FOR SELECT USING (true);
CREATE POLICY "country guides public select" ON public.country_guides FOR SELECT USING (true);
CREATE POLICY "videos public select" ON public.videos FOR SELECT USING (true);
CREATE POLICY "subscribers insert" ON public.subscribers FOR INSERT WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.increment_deal_click(deal_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.biletler
  SET clicks = COALESCE(clicks, 0) + 1,
      updated_at = NOW()
  WHERE id = deal_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Admin yazma/silme işlemleri uygulamada service_role key ile yapılır.

-- Profil Sayfası ve Premium Özellikler İçin Yeni Tablolar

-- 1. Favori Biletler Tablosu
CREATE TABLE IF NOT EXISTS public.user_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  bilet_id BIGINT REFERENCES public.biletler(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, bilet_id) -- Bir kullanıcı aynı bileti iki kez favorileyemez
);

-- 2. Kaydedilmiş AI Seyahat Planları Tablosu
CREATE TABLE IF NOT EXISTS public.user_trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  destination TEXT NOT NULL,
  trip_data JSONB NOT NULL, -- AI'ın ürettiği veriyi burada tutacağız
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security (RLS) Güvenlik Ayarları
ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_trips ENABLE ROW LEVEL SECURITY;

-- Kullanıcılar sadece kendi favorilerini görebilir, silebilir ve ekleyebilir
CREATE POLICY "Kullanıcılar kendi favorilerini yönetebilir" 
ON public.user_favorites 
FOR ALL 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

-- Kullanıcılar sadece kendi seyahat planlarını görebilir ve yönetebilir
CREATE POLICY "Kullanıcılar kendi planlarını yönetebilir" 
ON public.user_trips 
FOR ALL 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

-- Doğrulanmış Gezgin Sistemi Tablosu
CREATE TABLE IF NOT EXISTS public.travel_verifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  country_code TEXT NOT NULL,
  city_slug TEXT,
  verification_type TEXT NOT NULL, -- flight_ticket, boarding_pass, hotel_reservation, vs.
  verification_status TEXT DEFAULT 'pending', -- pending, approved, rejected, expired
  verified_at TIMESTAMPTZ,
  rejected_reason TEXT,
  proof_deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.travel_verifications ENABLE ROW LEVEL SECURITY;

-- Sadece kendi verisini görebilir
CREATE POLICY "Kullanıcılar kendi doğrulama kayıtlarını görebilir" 
ON public.travel_verifications 
FOR SELECT 
USING (auth.uid() = user_id);

-- Sadece kendisi için ekleyebilir
CREATE POLICY "Kullanıcılar kendi doğrulama taleplerini oluşturabilir" 
ON public.travel_verifications 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- KVKK ve Veri Silme Talepleri Tablosu
CREATE TABLE IF NOT EXISTS public.kvkk_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  request_type TEXT NOT NULL, -- delete_data, withdraw_consent, account_deletion
  status TEXT DEFAULT 'pending', -- pending, processed, rejected
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  processed_at TIMESTAMPTZ
);

ALTER TABLE public.kvkk_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Kullanıcılar kendi KVKK taleplerini görebilir"
ON public.kvkk_requests
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Kullanıcılar kendi KVKK taleplerini oluşturabilir"
ON public.kvkk_requests
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- İşletme İtirazları Tablosu
CREATE TABLE IF NOT EXISTS public.business_objections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_name TEXT NOT NULL,
  authorized_person TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  objection_type TEXT NOT NULL,
  content_url TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT DEFAULT 'pending', -- pending, reviewing, resolved, rejected
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Admin erişimi için RLS (Insert herkese açık olabilir ama tablo RLS ile korunmalı)
ALTER TABLE public.business_objections ENABLE ROW LEVEL SECURITY;

-- Yeni kayıt eklemeyi herkes yapabilir (anonim dahil, form üzerinden geldiği için)
CREATE POLICY "Herkes itiraz formu gönderebilir"
ON public.business_objections
FOR INSERT
WITH CHECK (true);

-- Select işlemlerini sadece Service Role Key (Admin) yapabilir.
-- İstemcide Select engellenmiştir.
