import type { EmergencyContact } from './types';

// Individually checked official sources; see SOURCE-AUDIT-20260926.md.
// Malaysia uses the current national 999 source instead of the older FCDO fire number.
export const EMERGENCY_CONTACTS: EmergencyContact[] = [
  {"country":"AE","category":"police","number":"999","sourceUrl":"https://www.gov.uk/foreign-travel-advice/united-arab-emirates/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AE","category":"ambulance","number":"998","sourceUrl":"https://www.gov.uk/foreign-travel-advice/united-arab-emirates/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AE","category":"fire","number":"997","sourceUrl":"https://www.gov.uk/foreign-travel-advice/united-arab-emirates/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AL","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/albania/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AL","category":"ambulance","number":"127","sourceUrl":"https://www.gov.uk/foreign-travel-advice/albania/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AL","category":"fire","number":"128","sourceUrl":"https://www.gov.uk/foreign-travel-advice/albania/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AT","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/austria/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AT","category":"police","number":"133","sourceUrl":"https://www.gov.uk/foreign-travel-advice/austria/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AT","category":"ambulance","number":"144","sourceUrl":"https://www.gov.uk/foreign-travel-advice/austria/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AT","category":"fire","number":"122","sourceUrl":"https://www.gov.uk/foreign-travel-advice/austria/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AU","category":"general","number":"000","sourceUrl":"https://www.gov.uk/foreign-travel-advice/australia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AU","category":"police","number":"000","sourceUrl":"https://www.gov.uk/foreign-travel-advice/australia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AU","category":"ambulance","number":"000","sourceUrl":"https://www.gov.uk/foreign-travel-advice/australia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AU","category":"fire","number":"000","sourceUrl":"https://www.gov.uk/foreign-travel-advice/australia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AZ","category":"police","number":"102","sourceUrl":"https://www.gov.uk/foreign-travel-advice/azerbaijan/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AZ","category":"ambulance","number":"103","sourceUrl":"https://www.gov.uk/foreign-travel-advice/azerbaijan/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"AZ","category":"fire","number":"101","sourceUrl":"https://www.gov.uk/foreign-travel-advice/azerbaijan/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"BA","category":"police","number":"122","sourceUrl":"https://www.gov.uk/foreign-travel-advice/bosnia-and-herzegovina/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"BA","category":"ambulance","number":"124","sourceUrl":"https://www.gov.uk/foreign-travel-advice/bosnia-and-herzegovina/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"BA","category":"fire","number":"123","sourceUrl":"https://www.gov.uk/foreign-travel-advice/bosnia-and-herzegovina/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"BE","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/belgium/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"BE","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/belgium/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"BE","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/belgium/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"BE","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/belgium/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CA","category":"general","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/canada/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CA","category":"police","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/canada/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CA","category":"ambulance","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/canada/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CA","category":"fire","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/canada/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CA","category":"coastguard","number":"+18004634393","sourceUrl":"https://www.gov.uk/foreign-travel-advice/canada/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CH","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/switzerland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CH","category":"police","number":"117","sourceUrl":"https://www.gov.uk/foreign-travel-advice/switzerland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CH","category":"ambulance","number":"144","sourceUrl":"https://www.gov.uk/foreign-travel-advice/switzerland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CH","category":"fire","number":"118","sourceUrl":"https://www.gov.uk/foreign-travel-advice/switzerland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CZ","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/czechia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CZ","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/czechia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CZ","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/czechia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"CZ","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/czechia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"DE","category":"police","number":"110","sourceUrl":"https://www.gov.uk/foreign-travel-advice/germany/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"DE","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/germany/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"DE","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/germany/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"DK","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/denmark/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"DK","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/denmark/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"DK","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/denmark/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"DK","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/denmark/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"EG","category":"police","number":"122","sourceUrl":"https://www.gov.uk/foreign-travel-advice/egypt/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"EG","category":"ambulance","number":"123","sourceUrl":"https://www.gov.uk/foreign-travel-advice/egypt/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"EG","category":"fire","number":"180","sourceUrl":"https://www.gov.uk/foreign-travel-advice/egypt/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"EG","category":"tourist-police","number":"126","sourceUrl":"https://www.gov.uk/foreign-travel-advice/egypt/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"ES","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/spain/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"ES","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/spain/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"ES","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/spain/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"ES","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/spain/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"FI","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/finland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"FI","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/finland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"FI","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/finland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"FI","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/finland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"FR","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/france/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"FR","category":"police","number":"17","sourceUrl":"https://www.gov.uk/foreign-travel-advice/france/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"FR","category":"ambulance","number":"15","sourceUrl":"https://www.gov.uk/foreign-travel-advice/france/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"FR","category":"fire","number":"18","sourceUrl":"https://www.gov.uk/foreign-travel-advice/france/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GB","category":"general","number":"999","sourceUrl":"https://www.gov.uk/guidance/999-and-112-the-uks-national-emergency-numbers","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GB","category":"police","number":"999","sourceUrl":"https://www.gov.uk/guidance/999-and-112-the-uks-national-emergency-numbers","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GB","category":"ambulance","number":"999","sourceUrl":"https://www.gov.uk/guidance/999-and-112-the-uks-national-emergency-numbers","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GB","category":"fire","number":"999","sourceUrl":"https://www.gov.uk/guidance/999-and-112-the-uks-national-emergency-numbers","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GB","category":"coastguard","number":"999","sourceUrl":"https://www.gov.uk/guidance/999-and-112-the-uks-national-emergency-numbers","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GE","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/georgia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GE","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/georgia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GE","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/georgia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GE","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/georgia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GR","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/greece/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GR","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/greece/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GR","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/greece/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"GR","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/greece/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"HR","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/croatia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"HR","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/croatia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"HR","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/croatia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"HR","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/croatia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"HU","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/hungary/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"HU","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/hungary/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"HU","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/hungary/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"HU","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/hungary/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"ID","category":"police","number":"110","sourceUrl":"https://www.gov.uk/foreign-travel-advice/indonesia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"ID","category":"ambulance","number":"118","sourceUrl":"https://www.gov.uk/foreign-travel-advice/indonesia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"ID","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/indonesia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IE","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/ireland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IE","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/ireland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IE","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/ireland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IE","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/ireland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IN","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/india/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IN","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/india/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IN","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/india/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IN","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/india/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IT","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/italy/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IT","category":"ambulance","number":"118","sourceUrl":"https://www.gov.uk/foreign-travel-advice/italy/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"IT","category":"fire","number":"115","sourceUrl":"https://www.gov.uk/foreign-travel-advice/italy/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"JP","category":"police","number":"110","sourceUrl":"https://www.gov.uk/foreign-travel-advice/japan/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"JP","category":"ambulance","number":"119","sourceUrl":"https://www.gov.uk/foreign-travel-advice/japan/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"JP","category":"fire","number":"119","sourceUrl":"https://www.gov.uk/foreign-travel-advice/japan/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"KR","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/south-korea/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"KR","category":"ambulance","number":"119","sourceUrl":"https://www.gov.uk/foreign-travel-advice/south-korea/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"KR","category":"fire","number":"119","sourceUrl":"https://www.gov.uk/foreign-travel-advice/south-korea/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MA","category":"police","number":"190","sourceUrl":"https://www.gov.uk/foreign-travel-advice/morocco/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MA","category":"ambulance","number":"150","sourceUrl":"https://www.gov.uk/foreign-travel-advice/morocco/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MA","category":"fire","number":"150","sourceUrl":"https://www.gov.uk/foreign-travel-advice/morocco/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MA","category":"gendarmerie","number":"177","sourceUrl":"https://www.gov.uk/foreign-travel-advice/morocco/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"ME","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/montenegro/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MX","category":"general","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/mexico/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MX","category":"police","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/mexico/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MX","category":"ambulance","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/mexico/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MX","category":"fire","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/mexico/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MY","category":"general","number":"999","sourceUrl":"https://www.malaysia.gov.my/en/categories/safety-and-community/public-safety/mers-999-emergency-line","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MY","category":"police","number":"999","sourceUrl":"https://www.malaysia.gov.my/en/categories/safety-and-community/public-safety/mers-999-emergency-line","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MY","category":"ambulance","number":"999","sourceUrl":"https://www.malaysia.gov.my/en/categories/safety-and-community/public-safety/mers-999-emergency-line","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"MY","category":"fire","number":"999","sourceUrl":"https://www.malaysia.gov.my/en/categories/safety-and-community/public-safety/mers-999-emergency-line","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NL","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/netherlands/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NL","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/netherlands/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NL","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/netherlands/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NL","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/netherlands/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NO","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/norway/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NO","category":"ambulance","number":"113","sourceUrl":"https://www.gov.uk/foreign-travel-advice/norway/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NO","category":"fire","number":"110","sourceUrl":"https://www.gov.uk/foreign-travel-advice/norway/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NZ","category":"general","number":"111","sourceUrl":"https://www.gov.uk/foreign-travel-advice/new-zealand/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NZ","category":"police","number":"111","sourceUrl":"https://www.gov.uk/foreign-travel-advice/new-zealand/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NZ","category":"ambulance","number":"111","sourceUrl":"https://www.gov.uk/foreign-travel-advice/new-zealand/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"NZ","category":"fire","number":"111","sourceUrl":"https://www.gov.uk/foreign-travel-advice/new-zealand/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"PL","category":"police","number":"997","sourceUrl":"https://www.gov.uk/foreign-travel-advice/poland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"PL","category":"ambulance","number":"999","sourceUrl":"https://www.gov.uk/foreign-travel-advice/poland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"PL","category":"fire","number":"998","sourceUrl":"https://www.gov.uk/foreign-travel-advice/poland/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"PT","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/portugal/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"PT","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/portugal/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"PT","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/portugal/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"PT","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/portugal/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"QA","category":"general","number":"999","sourceUrl":"https://www.gov.uk/foreign-travel-advice/qatar/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"QA","category":"police","number":"999","sourceUrl":"https://www.gov.uk/foreign-travel-advice/qatar/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"QA","category":"ambulance","number":"999","sourceUrl":"https://www.gov.uk/foreign-travel-advice/qatar/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"QA","category":"fire","number":"999","sourceUrl":"https://www.gov.uk/foreign-travel-advice/qatar/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"RS","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/serbia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"RS","category":"police","number":"192","sourceUrl":"https://www.gov.uk/foreign-travel-advice/serbia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"RS","category":"ambulance","number":"194","sourceUrl":"https://www.gov.uk/foreign-travel-advice/serbia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"RS","category":"fire","number":"193","sourceUrl":"https://www.gov.uk/foreign-travel-advice/serbia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"SA","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/saudi-arabia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Suudi Arabistan SIM kartın yoksa resmî rehber 112’yi öneriyor.","en":"Official guidance recommends 112 if you do not have a Saudi SIM card."}},
  {"country":"SA","category":"police","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/saudi-arabia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Suudi Arabistan SIM kartın yoksa 112’yi kullan.","en":"Use 112 if you do not have a Saudi SIM card."}},
  {"country":"SA","category":"ambulance","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/saudi-arabia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Suudi Arabistan SIM kartın yoksa 112’yi kullan.","en":"Use 112 if you do not have a Saudi SIM card."}},
  {"country":"SA","category":"fire","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/saudi-arabia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Suudi Arabistan SIM kartın yoksa 112’yi kullan.","en":"Use 112 if you do not have a Saudi SIM card."}},
  {"country":"SE","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/sweden/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"SE","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/sweden/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"SE","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/sweden/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"SE","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/sweden/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"SG","category":"police","number":"999","sourceUrl":"https://www.gov.uk/foreign-travel-advice/singapore/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"SG","category":"ambulance","number":"995","sourceUrl":"https://www.gov.uk/foreign-travel-advice/singapore/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"SG","category":"fire","number":"995","sourceUrl":"https://www.gov.uk/foreign-travel-advice/singapore/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TH","category":"general","number":"191","sourceUrl":"https://www.gov.uk/foreign-travel-advice/thailand/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TH","category":"police","number":"191","sourceUrl":"https://www.gov.uk/foreign-travel-advice/thailand/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TH","category":"ambulance","number":"1669","sourceUrl":"https://www.gov.uk/foreign-travel-advice/thailand/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TH","category":"fire","number":"199","sourceUrl":"https://www.gov.uk/foreign-travel-advice/thailand/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TH","category":"tourist-police","number":"1155","sourceUrl":"https://www.gov.uk/foreign-travel-advice/thailand/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TN","category":"police","number":"197","sourceUrl":"https://www.gov.uk/foreign-travel-advice/tunisia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Şehir ve kasabalarda polis.","en":"Police in towns and cities."}},
  {"country":"TN","category":"ambulance","number":"190","sourceUrl":"https://www.gov.uk/foreign-travel-advice/tunisia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TN","category":"fire","number":"198","sourceUrl":"https://www.gov.uk/foreign-travel-advice/tunisia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TN","category":"gendarmerie","number":"193","sourceUrl":"https://www.gov.uk/foreign-travel-advice/tunisia/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Kırsalda ve küçük köylerde Ulusal Muhafız.","en":"National Guard in rural areas and small villages."}},
  {"country":"TR","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/turkey/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TR","category":"police","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/turkey/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TR","category":"ambulance","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/turkey/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"TR","category":"fire","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/turkey/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"US","category":"general","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/usa/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"US","category":"police","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/usa/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"US","category":"ambulance","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/usa/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"US","category":"fire","number":"911","sourceUrl":"https://www.gov.uk/foreign-travel-advice/usa/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"VN","category":"police","number":"113","sourceUrl":"https://www.gov.uk/foreign-travel-advice/vietnam/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Acil hatlar Vietnamca hizmet veriyor; dil desteği gerekebilir.","en":"Emergency lines operate in Vietnamese; language assistance may be needed."}},
  {"country":"VN","category":"ambulance","number":"115","sourceUrl":"https://www.gov.uk/foreign-travel-advice/vietnam/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Acil hatlar Vietnamca hizmet veriyor; dil desteği gerekebilir.","en":"Emergency lines operate in Vietnamese; language assistance may be needed."}},
  {"country":"VN","category":"fire","number":"114","sourceUrl":"https://www.gov.uk/foreign-travel-advice/vietnam/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Acil hatlar Vietnamca hizmet veriyor; dil desteği gerekebilir.","en":"Emergency lines operate in Vietnamese; language assistance may be needed."}},
  {"country":"XK","category":"general","number":"112","sourceUrl":"https://www.gov.uk/foreign-travel-advice/kosovo/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25"},
  {"country":"XK","category":"police","number":"192","sourceUrl":"https://www.gov.uk/foreign-travel-advice/kosovo/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Cep telefonundan arama numarası.","en":"Number for calls from a mobile phone."}},
  {"country":"XK","category":"ambulance","number":"194","sourceUrl":"https://www.gov.uk/foreign-travel-advice/kosovo/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Cep telefonundan arama numarası.","en":"Number for calls from a mobile phone."}},
  {"country":"XK","category":"fire","number":"193","sourceUrl":"https://www.gov.uk/foreign-travel-advice/kosovo/getting-help","verifiedAt":"2026-09-26","reviewAfter":"2026-12-25","note":{"tr":"Cep telefonundan arama numarası.","en":"Number for calls from a mobile phone."}},
];
export function emergencyContacts(country: string) {
  return EMERGENCY_CONTACTS.filter(item => item.country === country.trim().toUpperCase());
}
export function dialUrl(number: string): string | null {
  const clean = number.replace(/[\s()-]/g, '');
  return /^\+?\d{2,15}$/.test(clean) ? `tel:${clean}` : null;
}
