import type { BlogPost, CountryGuide, FlightDeal } from "./types";
import { aviasalesUrl, siteSettings, trackedAffiliateUrl } from "./affiliate";

export const flightDeals: FlightDeal[] = [
  {
    id: 1,
    slug: "istanbul-dubai-ucuz-bilet",
    title: "İstanbul → Dubai fırsatı",
    origin: "İstanbul",
    destination: "Dubai",
    origin_code: "IST",
    destination_code: "DXB",
    price: 5490,
    currency: "TRY",
    airline: "Çoklu havayolu",
    travel_period: "Eylül - Kasım",
    trip_type: "Gidiş dönüş",
    visa_type: "e-vize",
    region: "Orta Doğu",
    image_url: "/travel-images/route-dubai.jpg",
    affiliate_url: aviasalesUrl({ origin: "IST", destination: "DXB" }),
    active: true,
    clicks: 0,
  },
  {
    id: 2,
    slug: "istanbul-roma-hafta-sonu",
    title: "Roma hafta sonu kaçamağı",
    origin: "İstanbul",
    destination: "Roma",
    origin_code: "SAW",
    destination_code: "FCO",
    price: 3790,
    currency: "TRY",
    airline: "Düşük maliyetli seçenekler",
    travel_period: "Ekim - Aralık",
    trip_type: "Gidiş dönüş",
    visa_type: "schengen",
    region: "Avrupa",
    image_url: "/travel-images/route-roma.jpg",
    affiliate_url: aviasalesUrl({ origin: "SAW", destination: "FCO" }),
    active: true,
    clicks: 0,
  },
  {
    id: 3,
    slug: "istanbul-baku-vizesiz",
    title: "Kimlikle Bakü rotası",
    origin: "İstanbul",
    destination: "Bakü",
    origin_code: "IST",
    destination_code: "GYD",
    price: 2990,
    currency: "TRY",
    airline: "Direkt uçuşlar",
    travel_period: "Yıl boyu",
    trip_type: "Gidiş dönüş",
    visa_type: "kimlikle",
    region: "Kafkasya",
    image_url: "/travel-images/route-baku.jpg",
    affiliate_url: aviasalesUrl({ origin: "IST", destination: "GYD" }),
    active: true,
    clicks: 0,
  },
  {
    id: 4,
    slug: "istanbul-saraybosna-vizesiz",
    title: "Saraybosna vizesiz Balkan rotası",
    origin: "İstanbul",
    destination: "Saraybosna",
    origin_code: "IST",
    destination_code: "SJJ",
    price: 3290,
    currency: "TRY",
    airline: "Direkt/aktarmalı",
    travel_period: "İlkbahar - Sonbahar",
    trip_type: "Gidiş dönüş",
    visa_type: "vizesiz",
    region: "Balkanlar",
    image_url: "/travel-images/route-saraybosna.jpg",
    affiliate_url: aviasalesUrl({ origin: "IST", destination: "SJJ" }),
    active: true,
    clicks: 0,
  },
  {
    id: 5,
    slug: "istanbul-tiflis-kimlikle",
    title: "Tiflis ekonomik şehir rotası",
    origin: "İstanbul",
    destination: "Tiflis",
    origin_code: "SAW",
    destination_code: "TBS",
    price: 2690,
    currency: "TRY",
    airline: "Direkt seçenekler",
    travel_period: "Mart - Haziran",
    trip_type: "Gidiş dönüş",
    visa_type: "kimlikle",
    region: "Kafkasya",
    image_url: "/travel-images/route-generic.jpg",
    affiliate_url: aviasalesUrl({ origin: "SAW", destination: "TBS" }),
    active: true,
    clicks: 0,
  },
  {
    id: 6,
    slug: "istanbul-tiran-yaz-rotasi",
    title: "Tiran & Ksamil yaz başlangıcı",
    origin: "İstanbul",
    destination: "Tiran",
    origin_code: "IST",
    destination_code: "TIA",
    price: 3490,
    currency: "TRY",
    airline: "Direkt/aktarmalı",
    travel_period: "Haziran - Eylül",
    trip_type: "Gidiş dönüş",
    visa_type: "vizesiz",
    region: "Balkanlar",
    image_url: "/travel-images/route-summer.jpg",
    affiliate_url: aviasalesUrl({ origin: "IST", destination: "TIA" }),
    active: true,
    clicks: 0,
  },
];

export const countryGuides: CountryGuide[] = [
  {
    id: 1,
    slug: "azerbaycan",
    country_code: "AZ",
    country_name: "Azerbaycan",
    continent: "Asya",
    region: "Kafkasya",
    emoji: "🇦🇿",
    icon_image: "/images/icon_generic_1781363859446.png",
    visa_status: "kimlikle",
    visa_note: "Türk vatandaşları yeni tip kimlikle giriş yapabilir.",
    avg_flight_price: 2990,
    flight_duration: "2 saat 45 dakika",
    best_months: "Nisan, Mayıs, Eylül, Ekim",
    airport_code: "GYD",
    is_popular: true,
    hero_image_url: "/travel-images/route-baku.jpg",
    content_markdown:
      "Bakü; kısa uçuş süresi, kimlikle giriş kolaylığı ve uygun şehir içi maliyetleriyle ilk yurt dışı seyahati için güçlü seçeneklerden biridir. Şehir merkezi, sahil hattı ve tarihi iç şehir kısa sürede gezilebilir.",
  },
  {
    id: 2,
    slug: "bosna-hersek",
    country_code: "BA",
    country_name: "Bosna Hersek",
    continent: "Avrupa",
    region: "Balkanlar",
    emoji: "🇧🇦",
    icon_image: "/images/icon_generic_1781363859446.png",
    visa_status: "vizesiz",
    visa_note: "180 gün içinde 90 güne kadar vizesiz kalış imkanı vardır.",
    avg_flight_price: 3290,
    flight_duration: "2 saat",
    best_months: "Mayıs, Haziran, Eylül",
    airport_code: "SJJ",
    is_popular: true,
    hero_image_url: "/travel-images/route-saraybosna.jpg",
    content_markdown:
      "<p><strong>Neden Bosna Hersek?</strong> Tarihi dokusu, çok kültürlü yapısı, hüzünlü yakın geçmişi ve yemyeşil doğasıyla hem kültürel hem de duygusal bir seyahat deneyimi sunar.</p><ul><li><strong>Gezilecek Yerler:</strong> Saraybosna Başçarşı (Bascarsija), Latin Köprüsü, Umut Tüneli, ikonik Mostar Köprüsü, Blagaj Tekkesi ve Kravice Şelaleleri mutlaka görülmesi gereken yerlerdir.</li><li><strong>Yeme-İçme:</strong> Balkan mutfağının incisi Cevapi (Cevapcici - Bosna köftesi), Boşnak böreği, begova çorbası ve geleneksel fincanda sunulan Boşnak kahvesi denenmeden dönülmemelidir. Porsiyonlar inanılmaz büyüktür ve fiyatlar çok ekonomiktir.</li><li><strong>Pratik Bilgi:</strong> Saraybosna ve Mostar arası tren yolculuğu, Avrupa'nın en manzaralı tren rotalarından biridir. Sadece 2-3 saat sürer ve çok ucuzdur.</li></ul><p>Vizesiz olması, düşük bütçeyle gezilebilmesi ve bize çok tanıdık gelen misafirperver kültürüyle kısa hafta sonu tatillerinin en popüler rotalarından biridir.</p>",
  },
  {
    id: 3,
    slug: "karadag",
    country_code: "ME",
    country_name: "Karadağ",
    continent: "Avrupa",
    region: "Balkanlar",
    emoji: "🇲🇪",
    icon_image: "/images/icon_generic_1781363859446.png",
    visa_status: "vizesiz",
    visa_note: "Türk vatandaşları turistik seyahatlerde vizesiz giriş yapabilir.",
    avg_flight_price: 3890,
    flight_duration: "1 saat 45 dakika",
    best_months: "Haziran, Eylül",
    airport_code: "TGD",
    is_popular: true,
    hero_image_url: "/travel-images/route-summer.jpg",
    content_markdown:
      "<p><strong>Neden Karadağ?</strong> Karadağ, Adriyatik kıyısındaki eşsiz plajları, Orta Çağ'dan kalma tarihi dokusu ve nispeten uygun bütçesiyle vizesiz rotaların vazgeçilmezidir.</p><ul><li><strong>Gezilecek Yerler:</strong> Muhteşem manzarasıyla Kotor Körfezi, gece hayatıyla meşhur Budva Eski Şehir (Stari Grad), lüks marinasıyla Porto Montenegro, ikonik Sveti Stefan adası, sakin Perast kasabası ve doğa severler için Durmitor Milli Parkı.</li><li><strong>Yeme-İçme ve Kültür:</strong> Taze deniz ürünleri, Balkan köftesi (Cevapi), siyah risotto ve yerel şaraplar oldukça meşhurdur. Porsiyonlar büyüktür ve fiyatlar diğer Avrupa sahil kasabalarına göre daha ulaşılabilirdir.</li><li><strong>Ulaşım Tavsiyesi:</strong> Tivat veya başkent Podgorica havalimanlarına inip araç kiralayarak tüm sahil şeridini 2-3 gün içinde keşfetmek en popüler ve konforlu rotadır.</li></ul><p>Kısa uçuş süresi ve vizesiz giriş avantajı nedeniyle özellikle yaz aylarında uzun deniz tatilleri veya bahar aylarında romantik hafta sonu kaçamakları için mükemmel bir destinasyondur.</p>",
  },
  {
    id: 4,
    slug: "arnavutluk",
    country_code: "AL",
    country_name: "Arnavutluk",
    continent: "Avrupa",
    region: "Balkanlar",
    emoji: "🇦🇱",
    icon_image: "/images/icon_generic_1781363859446.png",
    visa_status: "vizesiz",
    visa_note: "Türk vatandaşları turistik amaçlı vizesiz seyahat edebilir.",
    avg_flight_price: 3490,
    flight_duration: "1 saat 45 dakika",
    best_months: "Haziran, Eylül",
    airport_code: "TIA",
    is_popular: true,
    hero_image_url: "/travel-images/route-summer.jpg",
    content_markdown:
      "<p><strong>Neden Arnavutluk?</strong> Avrupa'nın Maldivleri olarak bilinen güney sahilleri, el değmemiş doğası ve Avrupa standartlarına göre son derece düşük bütçesiyle yükselen bir destinasyondur.</p><ul><li><strong>Gezilecek Yerler:</strong> Başkent Tiran'ın renkli sokakları ve Bunk'Art müzeleri; yaz ayları için Ksamil sahilleri, Saranda, tarihi berat kasabası (Bin Pencereli Şehir) ve doğa tutkunları için Theth Milli Parkı.</li><li><strong>Yeme-İçme:</strong> Taze deniz ürünleri, İtalyan mutfağına taş çıkaran pizzalar/makarnalar (İtalya'ya olan yakınlığı sebebiyle) ve Trileçe tatlısının en güzel hallerini burada bulabilirsiniz.</li><li><strong>Ulaşım Tavsiyesi:</strong> Toplu taşıma altyapısı çok gelişmiş olmadığı için, sahil şeridini ve dağ köylerini hakkıyla gezebilmek adına havalimanından araç kiralamak kesinlikle önerilir.</li></ul><p>Tiran, Ksamil ve Saranda hattı; yaz aylarında ekonomik deniz tatili arayanlar için öne çıkar. Erken rezervasyon ile çok uygun fiyatlara muazzam bir yaz tatili planlanabilir.</p>",
  },
  {
    id: 5,
    slug: "gurcistan",
    country_code: "GE",
    country_name: "Gürcistan",
    continent: "Asya",
    region: "Kafkasya",
    emoji: "🇬🇪",
    icon_image: "/images/icon_generic_1781363859446.png",
    visa_status: "kimlikle",
    visa_note: "Yeni tip kimlikle giriş yapılabilir.",
    avg_flight_price: 2490,
    flight_duration: "2 saat 15 dakika",
    best_months: "Mayıs, Haziran, Eylül, Ekim",
    airport_code: "TBS",
    is_popular: false,
    hero_image_url: "/travel-images/route-generic.jpg",
    content_markdown:
      "<p><strong>Neden Gürcistan?</strong> Pasaporta dahi ihtiyaç duymadan, sadece yeni tip T.C. kimlik kartınızla giriş yapabileceğiniz, vizesiz ötesi bir kolaylık sunan sınır komşumuzdur.</p><ul><li><strong>Gezilecek Yerler:</strong> Başkent Tiflis'in bohem kafeleri, Narikala Kalesi ve kükürt hamamları (Abanotubani); Karadeniz kıyısındaki modern Batum heykelleri (Ali ve Nino) ve botanik parkı; doğa tutkunları için Kazbegi dağları mutlaka görülmelidir.</li><li><strong>Yeme-İçme:</strong> Meşhur peynirli pide Haçapuri, büyük etli mantı Hinkali (Khinkali) ve kendine has yapım teknikleriyle dünyanın en eski şarap kültürlerinden biri olan Gürcü şarapları seyahatin tadını çıkarmanızı sağlar.</li><li><strong>Pratik Bilgi:</strong> Özellikle Artvin-Sarp sınır kapısından yürüyerek bile Batum'a geçmek mümkündür. Kimlikle giriş yapılabilmesi, ilk yurt dışı seyahati için bürokratik engelleri tamamen ortadan kaldırır.</li></ul><p>Tiflis; düşük bütçeli gastronomi, kültür ve hafta sonu seyahati için güçlü bir alternatiftir.</p>",
  },
  {
    id: 6,
    slug: "sirbistan",
    country_code: "RS",
    country_name: "Sırbistan",
    continent: "Avrupa",
    region: "Balkanlar",
    emoji: "🇷🇸",
    icon_image: "/images/icon_generic_1781363859446.png",
    visa_status: "vizesiz",
    visa_note: "Kısa süreli turistik seyahatlerde vize istenmez.",
    avg_flight_price: 3190,
    flight_duration: "1 saat 40 dakika",
    best_months: "Nisan, Mayıs, Eylül",
    airport_code: "BEG",
    is_popular: false,
    hero_image_url: "/travel-images/route-generic.jpg",
    content_markdown:
      "<p><strong>Neden Sırbistan?</strong> Tuna ve Sava nehirlerinin buluştuğu noktada kurulan başkent Belgrad, bitmeyen gece hayatı, festivalleri ve genç nüfusuyla Balkanlar'ın en hareketli rotasıdır.</p><ul><li><strong>Gezilecek Yerler:</strong> Belgrad Kalesi (Kalemegdan), bohem sokak Skadarlija, devasa Aziz Sava Katedrali, modern kafe ve barlarıyla ünlü Knez Mihailova Caddesi, ve Zemun bölgesi.</li><li><strong>Yeme-İçme:</strong> Izgara etlerin (Pljeskavica) ve hamur işlerinin ağırlıkta olduğu zengin bir Balkan mutfağı vardır. Skadarlija bölgesindeki geleneksel restoranlarda canlı müzik eşliğinde akşam yemeği oldukça popülerdir.</li><li><strong>Gece Hayatı:</strong> Belgrad, Avrupa'nın gece hayatı başkentlerinden biri olarak kabul edilir. Nehir üzerindeki yüzer kulüpler (Splavlar) yaz aylarında sabahın ilk ışıklarına kadar eğlence sunar.</li></ul><p>Hafta sonu kaçamağı için kısa uçuş avantajı, dinamik şehir hayatı ve ekonomik fiyatlarıyla ideal bir vizesiz destinasyondur.</p>",
  },
  {
    id: 7,
    slug: "makedonya",
    country_code: "MK",
    country_name: "Kuzey Makedonya",
    continent: "Avrupa",
    region: "Balkanlar",
    emoji: "🇲🇰",
    icon_image: "/images/icon_generic_1781363859446.png",
    visa_status: "vizesiz",
    visa_note: "Turistik ziyaretlerde 90 güne kadar vizesizdir.",
    avg_flight_price: 2890,
    flight_duration: "1 saat 25 dakika",
    best_months: "Mayıs, Haziran, Eylül",
    airport_code: "SKP",
    is_popular: false,
    hero_image_url: "/travel-images/route-generic.jpg",
    content_markdown:
      "<p><strong>Neden Kuzey Makedonya?</strong> Hem Osmanlı esintilerini taşıyan başkent Üsküp hem de muazzam doğası ve gölüyle ünlü Ohrid, vizesiz rotalar arasında sakinliği ve tarihi bir arada arayanlar için en bütçe dostu ülkelerden biridir.</p><ul><li><strong>Gezilecek Yerler:</strong> Üsküp'te heykellerle dolu Makedonya Meydanı, Taş Köprü, Eski Çarşı ve Matka Kanyonu; güneyde ise UNESCO mirası Ohrid Gölü ve çevresindeki tarihi kiliseler (özellikle St. John at Kaneo).</li><li><strong>Yeme-İçme:</strong> Balkan mutfağı burada da hakimdir; köfte, börek, kuru fasulye (Tavce Gravce), Trileçe ve taze göl balıkları denenmelidir.</li><li><strong>Pratik Bilgi:</strong> Üsküp ve Ohrid arası otobüslerle 3 saat sürer. Üsküp daha çok tarihi/kültürel bir tur, Ohrid ise doğa ve dinginlik (yazın ise plaj/göl tatili) arayanlara hitap eder.</li></ul><p>Uçak bileti genellikle uygun bulunur. Küçük bir ülke olduğu için 3-4 günlük kısa bir tatilde iki önemli şehrini de gezebilirsiniz.</p>",
  },
  {
    id: 8,
    slug: "kosova",
    country_code: "XK",
    country_name: "Kosova",
    continent: "Avrupa",
    region: "Balkanlar",
    emoji: "🇽🇰",
    icon_image: "/images/icon_generic_1781363859446.png",
    visa_status: "vizesiz",
    visa_note: "Turistik kısa seyahatlerde vize gerektirmeyen Balkan rotalarındandır.",
    avg_flight_price: 2790,
    flight_duration: "1 saat 40 dakika",
    best_months: "Nisan, Mayıs, Eylül, Ekim",
    airport_code: "PRN",
    is_popular: false,
    hero_image_url: "/travel-images/route-generic.jpg",
    content_markdown:
      "Priştine; kısa uçuş süresi, uygun ulaşım ve Balkan atmosferiyle hafta sonu seyahatleri için değerlendirilebilir.",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    slug: "ilk-kez-yurt-disina-cikacaklara-rehber",
    title: "İlk kez yurt dışına çıkacaklara pratik rehber",
    excerpt: "Pasaport, uçuş, havalimanı ve varış sonrası yapılacakları sade bir listeyle öğren.",
    category: "Başlangıç Rehberi",
    read_time: "6 dk",
    image_url: "/travel-images/discover.jpg",
    author: "Letsgo2Travel",
    published_at: new Date().toISOString(),
    content: `İlk yurt dışı seyahati heyecan verici olduğu kadar stresli de olabilir. Pasaport, vize, uçuş, havalimanı ve varış sonrası yapılacakları sade bir listeyle sizin için derledik.

### 1. Belgeler ve Hazırlık
Seyahate çıkmadan önce belgelerinizin eksiksiz olduğundan emin olun:
- **Pasaport ve Vize:** Gideceğiniz ülkenin vize isteyip istemediğini kontrol edin. Pasaportunuzun en az 6 ay geçerliliği olması önemlidir.
- **Konaklama ve Dönüş Bileti:** Sınır polisleri sıklıkla dönüş biletinizi ve nerede konaklayacağınızı sorar. Çıktılarını yanınızda bulundurun.
- **Seyahat Sağlık Sigortası:** Olası sağlık sorunlarına karşı mutlaka yaptırın.

### 2. Havalimanı Süreci
Havalimanında stres yaşamamak için:
- Uçuştan en az **2.5 - 3 saat önce** havalimanında olun.
- Online check-in işlemini 24 saat önceden yaparsanız zamandan tasarruf edersiniz.
- Bagaj kurallarına (sıvı kısıtlamaları, kg sınırı) mutlaka dikkat edin.

> ⚠️ **Uyarı:** Powerbank ve lityum pilli elektronik eşyalarınızı mutlaka el bagajınıza alın, uçak altı (kayıtlı) bagaja vermeyin.

### 3. İletişim ve İnternet (eSIM)
Yurt dışına adım attığınız an internete bağlı olmak hayat kurtarır. Eskiden fiziksel SIM kart aramak gerekirdi, artık eSIM ile çok daha kolay:
- Seyahate çıkmadan önce **[Airalo üzerinden eSIM paketlerine göz atın](https://airalo.pxf.io/c/5594042/1041180/13318)**.
- Paketi Türkiye'deyken satın alıp kurun, uçaktan inince hemen aktifleşsin.

### 4. Konaklama ve Ulaşım
Varış sonrası için planınızı önceden yapın:
- Havalimanından otele nasıl gideceğinizi araştırın (otobüs, tren veya Uber/Bolt).
- Konaklamanızı **[Booking.com üzerinden](https://www.booking.com/index.html?aid=2389146)** filtreleyerek iptal esnekliği olan yerlerden seçmeniz faydalıdır.
- Yanınızda her ihtimale karşı az miktarda nakit (Döviz) bulundurun, ancak pek çok ülkede kredi/banka kartı (temassız) rahatça kullanılır.
`,
  },
  {
    id: 2,
    slug: "vizesiz-ulkeler-nasil-secilir",
    title: "Vizesiz ülke seçerken nelere bakmalı?",
    excerpt: "Sadece vize durumuna değil; uçak fiyatı, şehir içi maliyet ve sezon etkisine de bakmalısın.",
    category: "Vizesiz Rotalar",
    read_time: "5 dk",
    image_url: "/travel-images/route-summer.jpg",
    author: "Letsgo2Travel",
    published_at: new Date().toISOString(),
    content:
      "Vizesiz rota seçerken uçak bileti toplam maliyetin sadece bir parçasıdır. Konaklama, yeme içme, şehir içi ulaşım ve sezon yoğunluğu seyahat bütçesini doğrudan etkiler. Balkanlar genelde kısa kaçamak için güçlüdür.",
  },
  {
    id: 3,
    slug: "ucuz-ucak-bileti-bulma-taktikleri",
    title: "Ucuz uçak bileti bulma taktikleri",
    excerpt: "Fiyat alarmı, esnek tarih ve alternatif havalimanı kullanarak daha iyi fırsatlar yakala.",
    category: "Ucuz Bilet",
    read_time: "7 dk",
    image_url: "/travel-images/live-flights.jpg",
    author: "Letsgo2Travel",
    published_at: new Date().toISOString(),
    content:
      "Ucuz bilet için tek bir güne bağlı kalma. Salı, çarşamba ve cumartesi dönüş kombinasyonlarını dene. İstanbul için hem IST hem SAW seçeneklerini kontrol et. Fiyat alarmı kurarak ani düşüşleri yakalayabilirsin.",
  },
  {
    id: 4,
    slug: "otel-secimi-icin-5-kontrol",
    title: "Otel seçerken 5 hızlı kontrol",
    excerpt: "Konum, iptal politikası, son yorumlar ve ulaşım maliyetiyle daha doğru konaklama seç.",
    category: "Konaklama",
    read_time: "4 dk",
    image_url: "/travel-images/discover.jpg",
    author: "Letsgo2Travel",
    published_at: new Date().toISOString(),
    content:
      "Otel seçerken yalnızca gecelik fiyata bakma. Merkeze ulaşım, yorum tarihi, iptal esnekliği, kahvaltı durumu ve havalimanı bağlantısı toplam seyahat konforunu belirler.",
  },
  {
    id: 5,
    slug: "esim-mi-roaming-mi",
    title: "eSIM mi roaming mi daha mantıklı?",
    excerpt: "Kısa seyahatlerde internet maliyetini ve kullanım kolaylığını karşılaştır.",
    category: "eSIM",
    read_time: "4 dk",
    image_url: "/travel-images/live-flights.jpg",
    author: "Letsgo2Travel",
    published_at: new Date().toISOString(),
    content:
      "eSIM, uyumlu cihazlarda varıştan önce interneti hazır hale getirir. Roaming ise operatöre göre pratik olabilir ancak ücretleri kontrol etmek gerekir. Gideceğin ülke, gün sayısı ve veri ihtiyacı karar verir.",
  },
];

export const affiliateCards = [
  {
    title: "eSIM internet",
    text: "Yurt dışında fiziksel SIM kart aramadan internet paketini seyahatten önce hazırla.",
    cta: "eSIM paketlerini gör",
    href: trackedAffiliateUrl({ provider: "airalo", url: siteSettings.airaloAffiliateUrl, sourcePage: "affiliate_cards" }),
  },
  {
    title: "Otel arama",
    text: "Konum, yorum, iptal esnekliği ve fiyat dengesine göre konaklama seçeneklerini karşılaştır.",
    cta: "Otelleri karşılaştır",
    href: trackedAffiliateUrl({ provider: "booking", url: siteSettings.bookingAffiliateUrl, sourcePage: "affiliate_cards" }),
  },
  {
    title: "Turlar & aktiviteler",
    text: "Şehir turu, müze bileti, tekne turu ve günlük aktivite seçeneklerini keşfet.",
    cta: "Aktiviteleri incele",
    href: trackedAffiliateUrl({ provider: "getyourguide", url: siteSettings.getYourGuideAffiliateUrl, sourcePage: "affiliate_cards" }),
  },
];
