import type {
  ChecklistItem,
  DestinationInfo,
} from "@/app/components/cockpit/types";

export const destinationOptions = [
  { code: "AE", name: "Birleşik Arap Emirlikleri" },
  { code: "DE", name: "Almanya" },
  { code: "IT", name: "İtalya" },
  { code: "TH", name: "Tayland" },
  { code: "GE", name: "Gürcistan" },
  { code: "BA", name: "Bosna-Hersek" },
  { code: "FR", name: "Fransa" },
  { code: "GB", name: "Birleşik Krallık" },
  { code: "US", name: "Amerika Birleşik Devletleri" },
  { code: "NL", name: "Hollanda" },
  { code: "ES", name: "İspanya" },
  { code: "JP", name: "Japonya" },
] as const;

const infoByCountry: Record<string, DestinationInfo> = {
  AE: {
    countryCode: "AE",
    countryName: "Birleşik Arap Emirlikleri",
    currencyCode: "AED",
    currencyLabel: "BAE Dirhemi",
    mockRateText: "1 AED ≈ 11,9 TL (demo)",
    plugTypes: ["G"],
    voltage: "230 V / 50 Hz",
    emergency: { general: "999", police: "999", ambulance: "998" },
    timezone: "UTC+4",
    language: "Arapça / İngilizce",
    quickTip: "Toplu alanlarda yerel kurallara ve kıyafet standartlarına dikkat et.",
  },
  DE: {
    countryCode: "DE",
    countryName: "Almanya",
    currencyCode: "EUR",
    currencyLabel: "Euro",
    mockRateText: "1 EUR ≈ 49,7 TL (demo)",
    plugTypes: ["C", "F"],
    voltage: "230 V / 50 Hz",
    emergency: { general: "112", police: "110", ambulance: "112" },
    timezone: "UTC+1 / UTC+2",
    language: "Almanca",
    quickTip: "Pazar günleri birçok mağaza kapalı olabilir; alışverişini önceden planla.",
  },
  IT: {
    countryCode: "IT",
    countryName: "İtalya",
    currencyCode: "EUR",
    currencyLabel: "Euro",
    mockRateText: "1 EUR ≈ 49,7 TL (demo)",
    plugTypes: ["C", "F", "L"],
    voltage: "230 V / 50 Hz",
    emergency: { general: "112", police: "112", ambulance: "118" },
    timezone: "UTC+1 / UTC+2",
    language: "İtalyanca",
    quickTip: "Yoğun turistik bölgelerde çanta ve telefon güvenliğine dikkat et.",
  },
  TH: {
    countryCode: "TH",
    countryName: "Tayland",
    currencyCode: "THB",
    currencyLabel: "Tayland Bahtı",
    mockRateText: "1 THB ≈ 1,31 TL (demo)",
    plugTypes: ["A", "B", "C", "O"],
    voltage: "230 V / 50 Hz",
    emergency: { general: "191", police: "191", ambulance: "1669" },
    timezone: "UTC+7",
    language: "Tayca",
    quickTip: "Tapınak ziyaretlerinde omuz ve dizleri örten kıyafet bulundur.",
  },
  GE: {
    countryCode: "GE",
    countryName: "Gürcistan",
    currencyCode: "GEL",
    currencyLabel: "Gürcistan Larisi",
    mockRateText: "1 GEL ≈ 16,2 TL (demo)",
    plugTypes: ["C", "F"],
    voltage: "220 V / 50 Hz",
    emergency: { general: "112" },
    timezone: "UTC+4",
    language: "Gürcüce",
    quickTip: "Kimlikle giriş kurallarını seyahatten hemen önce resmî kaynaktan doğrula.",
  },
  BA: {
    countryCode: "BA",
    countryName: "Bosna-Hersek",
    currencyCode: "BAM",
    currencyLabel: "Konvertibl Mark",
    mockRateText: "1 BAM ≈ 25,4 TL (demo)",
    plugTypes: ["C", "F"],
    voltage: "230 V / 50 Hz",
    emergency: { general: "112", police: "122", ambulance: "124" },
    timezone: "UTC+1 / UTC+2",
    language: "Boşnakça / Sırpça / Hırvatça",
    quickTip: "Küçük işletmeler için yanında bir miktar nakit bulundurmak faydalı olabilir.",
  },
  FR: {
    countryCode: "FR",
    countryName: "Fransa",
    currencyCode: "EUR",
    currencyLabel: "Euro",
    mockRateText: "1 EUR ≈ 49,7 TL (demo)",
    plugTypes: ["C", "E"],
    voltage: "230 V / 50 Hz",
    emergency: { general: "112", police: "17", ambulance: "15" },
    timezone: "UTC+1 / UTC+2",
    language: "Fransızca",
    quickTip: "Toplu taşımada biletini yolculuk sonuna kadar sakla.",
  },
  GB: {
    countryCode: "GB",
    countryName: "Birleşik Krallık",
    currencyCode: "GBP",
    currencyLabel: "İngiliz Sterlini",
    mockRateText: "1 GBP ≈ 57,4 TL (demo)",
    plugTypes: ["G"],
    voltage: "230 V / 50 Hz",
    emergency: { general: "999", police: "999", ambulance: "999" },
    timezone: "UTC / UTC+1",
    language: "İngilizce",
    quickTip: "Priz adaptörü ve temassız ödeme destekli bir kart hazırlamayı unutma.",
  },
  US: {
    countryCode: "US",
    countryName: "Amerika Birleşik Devletleri",
    currencyCode: "USD",
    currencyLabel: "ABD Doları",
    mockRateText: "1 USD ≈ 43,5 TL (demo)",
    plugTypes: ["A", "B"],
    voltage: "120 V / 60 Hz",
    emergency: { general: "911" },
    timezone: "Birden fazla saat dilimi",
    language: "İngilizce",
    quickTip: "Elektronik cihazlarının 120 V ile uyumlu olup olmadığını kontrol et.",
  },
  NL: {
    countryCode: "NL",
    countryName: "Hollanda",
    currencyCode: "EUR",
    currencyLabel: "Euro",
    mockRateText: "1 EUR ≈ 49,7 TL (demo)",
    plugTypes: ["C", "F"],
    voltage: "230 V / 50 Hz",
    emergency: { general: "112" },
    timezone: "UTC+1 / UTC+2",
    language: "Felemenkçe",
    quickTip: "Bisiklet yollarında yürümemeye ve yol işaretlerine dikkat et.",
  },
  ES: {
    countryCode: "ES",
    countryName: "İspanya",
    currencyCode: "EUR",
    currencyLabel: "Euro",
    mockRateText: "1 EUR ≈ 49,7 TL (demo)",
    plugTypes: ["C", "F"],
    voltage: "230 V / 50 Hz",
    emergency: { general: "112" },
    timezone: "UTC+1 / UTC+2",
    language: "İspanyolca",
    quickTip: "Yemek ve çalışma saatlerinin Türkiye’den daha geç olabileceğini hesaba kat.",
  },
  JP: {
    countryCode: "JP",
    countryName: "Japonya",
    currencyCode: "JPY",
    currencyLabel: "Japon Yeni",
    mockRateText: "100 JPY ≈ 28,9 TL (demo)",
    plugTypes: ["A", "B"],
    voltage: "100 V / 50-60 Hz",
    emergency: { general: "110", police: "110", ambulance: "119" },
    timezone: "UTC+9",
    language: "Japonca",
    quickTip: "Toplu taşımada sessizliğe ve sıra düzenine özen göster.",
  },
};

const fallbackDestination: DestinationInfo = {
  countryCode: "XX",
  countryName: "Destinasyon",
  currencyCode: "—",
  currencyLabel: "Kur bilgisi hazırlanıyor",
  mockRateText: "Demo kur verisi bulunmuyor",
  plugTypes: ["Kontrol et"],
  voltage: "Resmî kaynaktan doğrula",
  emergency: { general: "112 veya yerel acil numara" },
  timezone: "Yerel saat dilimini kontrol et",
  language: "Yerel dil",
  quickTip: "Vize, sağlık ve giriş kurallarını seyahatten önce resmî kaynaklardan doğrula.",
};

export function getDestinationInfo(countryCode: string): DestinationInfo {
  return infoByCountry[countryCode.toUpperCase()] ?? {
    ...fallbackDestination,
    countryCode: countryCode.toUpperCase(),
  };
}

export function createDefaultChecklist(): ChecklistItem[] {
  const now = new Date().toISOString();

  return [
    {
      id: crypto.randomUUID(),
      label: "Pasaport / kimlik geçerliliğini kontrol et",
      completed: false,
      category: "documents",
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      label: "Uçuş ve konaklama belgelerini indir",
      completed: false,
      category: "documents",
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      label: "Priz adaptörü hazırla",
      completed: false,
      category: "technology",
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      label: "İlaçları ve reçeteleri hazırla",
      completed: false,
      category: "health",
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      label: "eSIM veya internet paketini ayarla",
      completed: false,
      category: "technology",
      createdAt: now,
    },
  ];
}
